name: Mutlilevel-os

on: 
    
    push:
        branches: [main]


jobs: 
    ubuntu-job: 
        runs-on: ubuntu-latest

        steps: 
            - name : print system info
              run: |
                echo "Running os $(uname -a)"
                echo "Hostname is $(hostname)"
                echo "Current user is $(whoami)"

            - name: Check versions
              run: |
                echo "Docker version: $(docker --version)"
                echo "Python version: $(python --version)"
                echo "Node.js version: $(node --version)"
                echo "Git version: $(git --version)"
            
    windows-job:
        runs-on: windows-latest


        steps: 
            - name : print system info
              run: |
                echo "Running os $(uname -a)"
                echo "Hostname is $(hostname)"
                echo "Current user is $(whoami)"

    macos-job:
        runs-on: macos-latest


        steps: 
            - name : print system info
              run: |
                echo "Running os $(uname -a)"
                echo "Hostname is $(hostname)"
                echo "Current user is $(whoami)"