name: Secrects-Demo

on: 
    push:
        branches: [main]

jobs:
    prints-secret:
        runs-on: ubuntu-latest
        steps:
            - name: Check if secrects exists
              run: |
               if [ -z "${{ secrets.MY_SECRET_MESSAGE }}" ]; then
                echo "Secret is not set"
               else
                echo "Secret is set : true "
               fi

            - name: Print secret value
              run: echo "Secret value is ${{ secrets.MY_SECRET_MESSAGE }}"