name: Secrects-Demo

on: 
    push:
        branches: [main]

jobs:
    prints-secret:
        runs-on: ubuntu-latest
        steps:
            - name: Check if secrects exists
              run: |
               if [ -z "${{ secrets.MY_SECRET_MESSAGE }}" ]; then
                echo "Secret is not set"
               else
                echo "Secret is set : true "
               fi

            - name: Print secret value
              run: echo "Secret value is ${{ secrets.MY_SECRET_MESSAGE }}"

            - name: Use secret in a command
              env:
                SECRET_MESSAGE: ${{ secrets.MY_SECRET_MESSAGE }}
              run: echo "Using secret in safely 

            - name: create a log file
              run: echo "This my log file content $(date) " > log.txt

            - name: Upload log file as artifact
              uses: actions/upload-artifact@v3
              with:
                name: log-file