name: Self hosted test

on: 
  workflow_dispatch: 


jobs: 
 self-hosted-runner: 
  runs-on: [self-hosted, my-linux-runner]
  steps: 
    - name: print machine info
      run: | 
        hostname
        pwd
        touch test-file.txt
        ls -la

